### ISSUE TITLE
Service pre-configured with SignalR core

### ISSUE THREAD

**Issue by ewinnington** [stevejgordon/IHostedServiceAsAService#2]
I would love if you added an IHostedService with SignalR pre-configured.

**Comment by stevejgordon** [comment]
Hi @ewinnington! Thanks for the suggestion. 

For the scope of this sample, this doesn't really fit with what I intended to demonstrate (setting up a Generic Host app which can be run as a Windows service). 

I'm interested to hear what you'd like to achieve with SignalR and IHostedService / Generic host concepts? It could form a future sample, blog post, although I've not dug back into SignalR much (to date).

**Comment by ewinnington** [comment]
I was looking at using SignalR as a replacement for [WCF server side](https://github.com/dotnet/wcf/issues/2695) on .net core running on Windows. I was hoping to host [CoreWF](https://github.com/dmetzgar/corewf) in a service and communicate with it using SignalR. 

On the full framework, I have a set of windows services which host Workflow Foundation and expose a WCF interface to start / query / cancel workflows.

Based on your sample, I've created a service that [hosts signalR](https://github.com/ewinnington/HostedWFcore/blob/master/HostedWFcore/Services/SignalRCommunicationService.cs) in console mode / debug, but when running as a service stays stuck on "Starting" even though it responds to calls.

Thanks for the discussion, feel free to close the issue if you want.
